version: '3.8'
services:
  jupyter-lab:
    image: nvcr.io/nvidia/tensorflow:24.01-tf2-py3
    container_name: research-lab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --notebook-dir='/workspace'